"""Reusable API and inter-agent data contracts."""

from backend.schemas.common import (
    AgentResult,
    AgentTask,
    Case,
    Citation,
    Document,
    HealthResponse,
    RootResponse,
    VerificationResult,
)
from backend.schemas.retrieval import (
    RetrievalFilters,
    RetrievalMetadataResponse,
    RetrievalMode,
    RetrievalResultResponse,
    RetrievalSearchRequest,
    RetrievalSearchResponse,
    RetrievalTaskContext,
)
from backend.schemas.verification import (
    CitationStatus,
    CitationValidationResult,
    ClaimStatus,
    ClaimVerificationResult,
    LegalClaim,
    OverallVerificationStatus,
    ResponsibleAIWarning,
    RetrievedEvidence,
    SourceMetadata,
    VerificationIssueCode,
    VerificationRequest,
    VerificationResponse,
    WarningSeverity,
)

__all__ = [
    "AgentResult",
    "AgentTask",
    "Case",
    "Citation",
    "Document",
    "HealthResponse",
    "RetrievalFilters",
    "RetrievalMetadataResponse",
    "RetrievalMode",
    "RetrievalResultResponse",
    "RetrievalSearchRequest",
    "RetrievalSearchResponse",
    "RetrievalTaskContext",
    "RootResponse",
    "VerificationResult",
    "CitationStatus",
    "CitationValidationResult",
    "ClaimStatus",
    "ClaimVerificationResult",
    "LegalClaim",
    "OverallVerificationStatus",
    "ResponsibleAIWarning",
    "RetrievedEvidence",
    "SourceMetadata",
    "VerificationIssueCode",
    "VerificationRequest",
    "VerificationResponse",
    "WarningSeverity",
]
